spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youyi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: qq12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 6000
      minimum-idle: 1
      idle-timeout: 60000
      maximum-pool-size: 5
      auto-commit: true
      pool-name: MyHikari
      connection-test-query: select 1
